# можно использовать %time_sec% - будет выдавать оставшееся время в секундах.
# [MESSAGE] - сообщение. Можно использовать цвета ( Пример: &a&lСпасибо за скачивание! )
# [TITLE] - ВЕРХНИЙ ТАЙТЛ;НИЖНИЙ ТАЙТЛ
# [SOUND] - ЗВУК;ГРОМКОСТЬ;СКОРОСТЬ ВОСПРОИЗВЕДЕНИЯ
# %time% время кулдауна.

commands: # команда перезагрузки
  no-perm: '&cУ Вас нет прав.'

cooldown: 600 # в секундах

first-join-actions: # что будет делать при первом заходе игрока?
  - '[MESSAGE] &r'
  - '[MESSAGE] &eТак как вы присоеденились на сервер первый раз,'
  - '[MESSAGE] &eвам наложены ограничения на чат.'
  - '[MESSAGE] &r'
  - '[TITLE] &aДобро пожаловать!;&fВаш чат заблокирован на некоторое время!'
  - '[SOUND] ENTITY_VILLAGER_YES;1;1'
  -
chat-lock-actions: # что будет делать если игрок пишет в чат но ещё не наиграл нужное время?
  - '[MESSAGE] &r'
  - '[MESSAGE] &cПодождите ещё %time% перед отправкой сообщений.'
  - '[MESSAGE] &r'
  - '[TITLE] &cЧат заблокирован.;&fПодождите: &e%time%'
  - '[SOUND] ENTITY_VILLAGER_NO;1;1'

lock-commands: # если хотите отключить просто уберите все строки
  - 'm'
  - 'w'
  - 'r'
  - 'tell'
  - 'msg'
  - 'say'

block-commands: # блокировка команд с :
  enable: true
  actions:
    - '[MESSAGE] &r'
    - '[MESSAGE] &cКоманды с : запрещены.'
    - '[MESSAGE] &r'
    - '[TITLE] &cЗАБЛОКИРОВАНО!;&fКоманды с : запрещены.'
    - '[SOUND] ENTITY_VILLAGER_NO;1;1'

command-lock-actions: # что будет делать если игрок ввел запрещенную команду
  - '[MESSAGE] &r'
  - '[MESSAGE] &cПодождите ещё %time% перед использованием команды.'
  - '[MESSAGE] &r'
  - '[TITLE] &cКоманда не доступна.;&fПодождите: &e%time%'
  - '[SOUND] ENTITY_VILLAGER_NO;1;1'
